### ISSUE TITLE
GameVault+ Subscription

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#151]
## Introduction
I wish to propose a set of premium, nice-to-have features as an optional upgrade for a particular user segment who want to back our platform as we can't rely solely on donations to run this.

## General conditions
- The subscription for these extra features will be applicable on an individual basis, for each client's computer and not for the entire server.

- The subscription will grant access to exclusive "nice-to-have" features. These features are totally optional and can be easily canceled without significant loss for the user.

- It is important to us that the subscription remains affordable for our users. Based on a poll, users have expressed willingness to pay between $10 and $20 USD per client, billed annually.
  - we calculated all the costs, made comparisons with other services and looked at our previous donations and agreed on a price of €/$ 4.99 per month and €/$ 49.90 per year

- We understand that some users may still cant or don't want to afford this subscription. People should be "able to tinker" their way around the subscription if they really need them

- **The core product** without the nice-to-have features will remain free. This subscription is to support us as developers.

## Possible Nice to Have Premium Features
- Uploading Games to the Server
- Virus Scan of Downloaded Games
- Themes
- Servers List & Multi-Server Connection
- Uploading animated Pictures
- Playnite Integration
- Cloud Saves ([Ludusavi](https://github.com/mtkennerly/ludusavi) integration?)

### Client
- [x] Implement Login in GameVault App
- [x] Design GameVault+ Tab
- [x] Implement GameVault+ Tab
- [x] Connect to Customer Backend using Token
- [x] GameVault+ for Offline Mode?
- [x] Implement Access to Stripe Billing
- [x] Implement & Test Paywall for feature set

### Phalco.de Website
- [x] Add link to register and log in
- [x] (?) Manage account?
- [x] (?) Own register/login form?
- [x] (?) Show my purchases

### Server
- [x] Set up Stripe Billing
- [x] Plan Backend Server to handle all the premium stuff
- [X] Set up IAM system
- [X] Set up Backend Application
- [X] Set up Authentication and Authorization
- [x] Dockerize
- [x] Design Customer Backend API
- [x] Design Data Models
- [x] Implement amn Test APIs
- [x] Set up Database
- [x] Set up Database Migrations
- [x] Connect Stripe Webhooks

### General
- [x] Conduct brainstorming session for feature set
- [x] Decide for prices and set them in Stripe Billing

### Remaining Work for GameVault+ Early Access Release
- [X] Code Review and Merge for https://github.com/Phalcode/gamevault-app/pull/360 (thank you so much @Zallist)
- [x] Set Dates
- #363
- #364
- #365
- Implement Paywall for #144
- #366
- https://github.com/Phalcode/gamevault-backend/issues/9
- #367
- #368
- #369
- #370

**Comment by ChaosTherum** [comment]
So my suggestion rather than locking features behind a paywall would be offer essentially a white-glove installer, or virtual machine image for paying customers. 

At the very least I would hardly call uploading from the client would be a non-significant loss. Same for themes, sure it doesn't change functionality for the most part but it could unfairly restrict users who are colorblind from building themes for themselves.

Or are you saying that once a server has 1000 active users these restrictions would kick in? I could see that being much more reasonable but putting some of these restrictions on an admin that hosts for two or three room mates, seems a bit off to me. But then again I tend to be a free software extremist.

It might be worth setting up a Patreon and see how many bites you get, I know at least for myself I refused to pay for MediaMonkey for decades but in that same time I've been subscribed to the Patreons of multiple developers that distribute their applications completely freely.

**Comment by Alfagun74** [comment]
@ChaosTherum Thank you for your suggestions, but this software isn't intended for enterprise use. No one is asking for a white-glove service or a virtual machine setup.

People want value for their money, and the only way to provide it is by offering additional features.

The proposed option to upload games from the client is purely for convenience. Currently, it's not even possible in the full release version. It was not even requested by a single user either. This feature is just meant to make it easier to transfer games to your server. You can still use `scp game.zip server` or your current method if you prefer.

I don't see why colorblind people would have a hard time. For reference, take a look at Steam's interface. We might consider offering an additional bright mode or high contrast theme, but full customization with custom themes is more of a nice-to-have feature.

Regarding the 1000 users requirement: It's certainly not a per server requirement, that's for sure. Let's be realistic here. A gamevault server is most likely to serve a small community, consisting of close friends and family, perhaps 8-10 people at most.

The 1000 users represent the number of active users we aim to acquire for this app before considering to launch a monetization model. Having a substantial user base would ensure that there is a significant number of potential clients interested in purchasing something like GameVault+.

By the way, just to let you know, we already have a Ko-Fi page. It's linked almost everywhere. However, the fact that you were unaware of it indicates once again that it's not sufficient for sustaining our business. 

Lastly, let's look at this condition:

> people should be "able to tinker" their way around the subscription if they really need them

We are completely fine with you modifying the source code to add `return true;` wherever you encounter a paywall for your personal use. This should be sufficient to meet anyone's freebie or FOSS mentality. If you truly desire those additional features, go ahead.

However, if you prefer a simpler approach and wish to support our hard work and business, subscribing for 10-20 USD per year would be greatly appreciated. The amount is quite affordable and not a financial burden for most people. The financial support is crucial as we invest our free time and make sacrifices with our families to provide you with this software. We seriously considered going FOSS. However, based on our experience, it's not feasible for running a business. It almost always results in developers sacrificing their time, basically as volunteers, without receiving adequate compensation for years.

If you're ready for a jaw drop, take a look at the plex/jellyfin example here: https://gamevau.lt/blog/2023/07/13/

**Comment by teambvd** [comment]
> > people should be "able to tinker" their way around the subscription if they really need them

To see this mentality, it's honestly heartwarming. I'd happily chip in a dollar or two a month just to show some support, regardless of the ability to work around it - the fact that you wish to design the system with that capability in mind, it makes me feel I'd be *more* likely to contribute than otherwise. I've got to set aside some time to play with this, and have been meaning to since hearing about it on the selfhosted podcast, but if it all ends up being as great as what I'm hearing and reading from others... I'm sold.

That being said, couple things on the payment side - 
* Could you consider Librepay in addition to Ko-fi? Just wanting to stay in the FOSS (or 'near-FOSS' as here) ecosystem wherever possible
* With an amount under, say $25USD, I'd recommend just offering it as a yearly recurring vs monthly - fees will eat your lunch otherwise, though I'm sure this has probably already crossed your mind!

**Comment by Alfagun74** [comment]
@teambvd thank you for the kind words.

We never heard of librepay and will take look at it.

We actually did not think about the fees and we're going to consider it when doing the maths later at some point. We first want to make sure we have the set of nice features ready before we think about the money. 😊😊

**Comment by Alfagun74** [comment]
@teambvd Liberapay is awesome [we just signed up](https://liberapay.com/Phalcode/) Feel free to be our first supporter there 🥰

**Comment by UnholyVision** [comment]
My two cents or pence.

- Servers List & Multi-Server Connection
I don't see myself connecting to multiple servers, so no opinion on this.

- Uploading Games to the Server & Virus Scan of Downloaded Games
If this was for people assigned to be allowed to do this that were not the server owner. Then perhaps this would be worth it in a subscription. Maybe if it's on a local IP it's allowed and anything outside the network is part of a subscription.

- Cloud Saves
I think the client should provide this free, but maybe provide a Cloud+ like package. Where a backup of only game saves are uploaded to the cloud and maybe tack in a game save sharing option. 

- Themes
This should be free, unless you maybe make a few premium like themes. Because most people will likely set it and forget it. There isn't much of a pull in my opinion for a subscription on this. Yet, I could see this like a donation almost if premium themes that could be purchased. I would even potentially grab a theme or two. If there was something I liked and it was reasonably priced.

- Random Ideas
I would say, do something similar to say Plex or Emby. Have a service to tunnel out your access to your content outside your network, using GameVault servers. Though if someone wants to set up a VPN and/or reverse proxy out and whatever else they can, but the easier way is to pay for the subscription. As it's more of a one click fix. 

If you want to take it a step further, offer a tunneling method. Where a lan game could be tunneled outside the home network. I personally could get behind paying for something like this. It would require some infrastructure I understand that, but it would make the whole gaming experience with this client a lot more complete.

**Comment by ShadowPeo** [comment]
Cloud Saves could possibly work, do not know but you may be able to leverage the work of https://www.gamesave-manager.com/ to do this.

What I was going to suggest (even though it would put me in the pay group so do not think I am avoiding it myself here) is go with your first assumption of "Nice to Have" features, with LDAP/OAUTH/SAML being one of them, those who are using this kind of service would be the more "serious" ones I should think.

**Comment by BradleyShaner** [comment]
I can't see myself paying yearly for cloud saves but that's definitely something I would donate/pay one time for.

That would be a big undertaking (I've worked my own save manager a few years ago). Maybe you could offer the free cloud save version by allowing users to define locations for each game and the paid version has a curated and constantly updated list of save locations. Also being able to "share" a game save with a friend would be really neat.

**Comment by Toylerrr** [comment]
Adding my 2c here from issue #330 

GV+ Additions:

-     [App packager](https://github.com/Toylerrr/gamevault-it): Like my applet (but better) built into the GameVault app make it package a zip with the best/optimal settings to upload to server.
-     Upload from client
-     Hand selected free non-DRM games that people can auto add to their self hosted instance.
-     Linux/Steamdeck app: (also available via one-time license)
-     Client media: trailers and extra metadata besides the basic that is currently included from RAWG.
-     Big Picture

**Comment by Alfagun74** [comment]
Ive managed to set up a Spring Kotlin Customer Backend Application, along with auth etc. Going to update the ticket accordingly.

**Comment by teambvd** [comment]
> I can't see myself paying yearly for cloud saves but that's definitely something I would donate/pay one time for.

I've always felt like if something would have a 'recurring cost' associated with it to the platform (storing, syncing, and backing up {multiple copies for DR} cloud saves in this case), it made more sense to have a recurring payment to offset that cost. I'm not sure a one-time fee would make sense for this one, at least to me, and just as I've been thinking on it recently.

The thing that makes me question the one-time vs recurring for things that have recurring costs are the various companies that've had 'lifetime' one-time payments as an option, and come to find it bite them in the rear later.

Plex for example (ignoring the myriad problematic actions they've undertaken over the last handful of years): I've had plex since it was a little open source XBMC fork, probably over 15 years now, and I've had plex pass since there was a plex pass to have... I'm definitely costing them money at this point, as things like the extra's and some of their content matching tools call out to licensed services - licenses they have to renew each year. Not to mention the bandwidth costs incurred when the proxy relay is used O.o

Many usenet indexers have had to do away with their lifetime subscriptions, as even though each API call is relatively cheap, a single user with a couple applications hitting it each day definitely adds up. Not within a month, or even a year, but 5 years? 10? More?

Anyway, apologies for the bit of a rant here, certainly wasn't my intent! Just hoping this adds to the conversation somehow, hopefully

**Comment by Alfagun74** [comment]
> If a cost is recurring, then yes a subscription is entirely reasonable. Though personally for me, I would want "cloud" saves on my personal server, at which point there should not be any recurring costs on Phalcode.

@nosyrbllewe While we have no direct costs from GV+ users (yet), we do have a lot of indirect costs to maintain and expand the application suite. Think of GameVault+ as something like a Patreon subscription that supports us as developers while unlocking some nice features.

**Comment by Alfagun74** [comment]
closed in favour of sub-tasks
