### ISSUE TITLE
Box Arts are Cut off

### ISSUE THREAD

**Issue by 46620** [Phalcode/gamevault-app#159]
**Describe the bug**
A lot of cover art gets cut due to their size

**To Reproduce**
1. Either manually add box art or use RAWG to pull one

**Expected behavior**
Image is scaled to correct size

**Desktop (please complete the following information):**
 - OS: Windows 11

**Screenshots**
![image](https://github.com/Phalcode/gamevault-app/assets/29524794/77d4103d-fc85-4eba-b179-c574f5e9a7ce)

[Phonk cats](https://steamcdn-a.akamaihd.net/steam/apps/2430790/library_600x900_2x.jpg) and [Anarcute](https://assets-prd.ignimgs.com/2022/05/10/anarcute-button-1652166711607.jpg) images are custom uploads, with the original images linked in this post, and the Five Nights at Freddy's games are the stock images pulled from RAWG.

**Comment by Alfagun74** [comment]
Do you **really** use Windows 11 though? Or is it Linux or a VM ?

I remember @Yelo420 introduced some antics that re-compress the box art based on the primary display's resolution or something. Perhaps that feature isn't very useful when running in a VM since it can resize. Maybe you should reconsider that compression, @Yelo420, or even eliminate it completely since the server already compresses every image.

**Comment by Alfagun74** [comment]
on a side note all box arts are pulled from Google, not RAWG. RAWG only has wallpaper/screenshot-like images

**Comment by Alfagun74** [comment]
Nevermind i thought the problem was the blurry image and it was rescaled too bad, but i know am aware that this image is just some hentai you wanted to censor and your actual problem is that the boxarts are cut off 😆 

@Yelo420  What is the aspect ratio of those boxes? The common box art aspect ratio in the industry 2:3. (for example 600px width x 900px height)

**Comment by Yelo420** [comment]
Current aspect  ratio is 4:5 (with your example 720px width x 900px height).

I will change that.

**Comment by 46620** [comment]
@Alfagun74 it's a Windows VM I use for video editing when I need premiere, but I do have a bare metal windows machine I plan to use this with after auto extracting is finished. and the blurred image isn't a full hentai game, just has a very.. interesting cover photo

**Comment by Yelo420** [comment]
Fixed in the next version
