### ISSUE TITLE
(Optionally) Show total disk size before download starts

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#165]
**Is your feature request related to a problem? Please describe.**
Available disk size may not meet the space required to download, extract and install the game.

**Describe the solution you'd like**
Related to #164, the size required to install a game should be shown next to the total disk size available at the install/download location. This should take into consideration the requirement to have both the archive, installer, and game files in place at the same time.

**Describe alternatives you've considered**
Unsure of an alternative. Without the above a user could easily run into a situation where they are simply stuck between extract and install, or download and extract.

**Additional context**
GV should likely also be able to gracefully handle such edge cases where disk space runs out *and automatically revert to prevent problems on the local machine.*

**Comment by Alfagun74** [comment]
Your question seems a bit complicated. The tools that download and extract files already check if there's enough space on your computer. It's important for users to manage their storage space wisely. Figuring out the precise size needed for installing the game is quite tricky and might make the screen look busy with different numbers. Automatically reversing actions because of low storage space could interrupt things and cause unexpected results. It's a good idea not to install a 150GB game if you only have 200GB of space available.
