### ISSUE TITLE
"App is still running in the system tray" shouldn't be showing every time

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#173]
**Describe the bug**
Every single time GV is closed to tray, the user is reminded that "App is still running in the system tray." This is excessive, and this notification only really needs to be shown once, if at all.

**To Reproduce**
1. Open GV
2. Close to tray

**Expected behavior**
This notification only really needs to be shown the first time the UI is closed. 

Todo:
- [ ] should only show once per installation

**Comment by Alfagun74** [comment]
Good idea, we'll configure it so that each time you launch Gamevault initally, you receive only one notification when you close it for the first time. Subsequent closing and opening from the system tray won't generate a notification unless you completely restart the application. Would that solution make you satisfied?

**Comment by KairuByte** [comment]
Honestly, I think it only needs to be shown *once* for the lifetime of the installation of GV. Either that, or add a "never show me this again" option to the notification.

**Comment by Alfagun74** [comment]
Once in a lifetime isn't an option because the user might miss it. I'm not sure if Windows 10/11 has the "never show me again" feature implemented with the Windows SDK.

An idea i had is that we could add a Notifications Tab in the Settings in the future. This way, you can easily and precisely choose which notifications you want to receive and which ones you don't want to see. But you can create another feature request for that if you desire. 

But for us this "bug" is fixed with the once-per-session logic described above for now.

**Comment by Wh1t3Rose** [comment]
I can't think of a single other app that behaves the way (Once per session) you describe @Alfagun74. I agree with @KairuByte  that it should be only once for that install. I don't have a single other app on my PC that shows a notification everytime I minimize it to tray.

**Comment by KairuByte** [comment]
That was my main thought as well. In fact, I've noticed fewer and fewer apps even alerting on the first minimize.

**Comment by Alfagun74** [comment]
Well then people would complain that the app runs in background without their knowledge, and didn't restart properly because they don't understand that the app didn't exit completely.

**Comment by KairuByte** [comment]
One other potential, have the app close to taskbar, notify the first time, but ensure that any other attempt to open it opens that same instance. *If* that isn't how it's already handled of course.

**Comment by Alfagun74** [comment]
Poll Results say it should show once per installation. Just make a user config entry after the first one @Yelo420
