### ISSUE TITLE
RAWG (or other database) button on library entry

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#223]
**Is your feature request related to a problem? Please describe.**
Sometimes data is incorrect, or you just want to see the source of the information provided. 

**Describe the solution you'd like**
A button which takes you to the RAWG (or applicable database if/when more are added) site would be quite helpful.

Edit: To be clear, I am speaking of incorrect data *on the external database* and **not** in GV. Updating the external database and forcing a recache would solve the issue, and a button to take you to that external database is what is being asked for.

**Comment by Alfagun74** [comment]
The GameVault-Backend in its current implementation does not know where data in specific fields is from, because rawg data just overwrites the games data. This may change when [this](https://github.com/Phalcode/gamevault-backend/issues/161) gets implemented.

Also rawg database entries dont contain links to rawg.io and you cant navigate their website using rawg-IDs so there is no way to bring you there.

**Comment by KairuByte** [comment]
Oh, I never even considered that their API may not give you a way to get to the site from the data provided by the API... in that case, this can likely be closed, but I'll dig around and see if I can find a solution and poke you if I find one.
