### ISSUE TITLE
Prepare Release

### ISSUE THREAD

**Issue by Yelo420** [Phalcode/gamevault-app#280]
Final adjustments for the Library UI Change
- [x] UPLOAD DEVELOPER FLIGHT PACKAGE TO TEST EARLY ACCESS PLEASE
- [x] Edit User Popup and use SVG Edit icon to open it like used for game settings
- [x] [Setting to show Rawg Title instead of File Title in GameView](https://github.com/Phalcode/gamevault-app/issues/274)
- [x] Password fields won't reset after registering a user
- [x] After uploading an image, disable save button until change again
- [x] Add and Link Documentation Pages
  - [x] Game Settings -> Installation: https://gamevau.lt/docs/client-docs/gui#installation
  - [x] Game Settings -> Launch Options: https://gamevau.lt/docs/client-docs/gui#launch-options
  - [x] Game Settings -> Edit Images: https://gamevau.lt/docs/client-docs/gui#edit-images
  - [x] Game Settings -> RAWG Integration: https://gamevau.lt/docs/client-docs/gui#rawg-integration
  - [x] User Settings -> Edit Images: https://gamevau.lt/docs/client-docs/gui#edit-images-1
  - [x] User Settings -> Edit Details: https://gamevau.lt/docs/client-docs/gui#edit-details
  - [x] Installed Games -> No Games Found Troubleshooting: https://gamevau.lt/docs/troubleshooting/#games-not-appearing-in-the-installations--servers-list
  - [ ] Server Tab -> Offline Troubleshooting: https://gamevau.lt/docs/troubleshooting/#unable-to-connect-to-server--500-internal-server-error
  - [x] Server Tag -> No games found troubleshooting: https://gamevau.lt/docs/troubleshooting/#games-not-appearing-in-the-installations--servers-list
- [x] Make Save and Find Images button same size
- [x] Implement Converter for Progress States
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/5cea3d2a-5280-4521-9967-067330b12370)
- [x] Update Screenshots on Microsoft Store and Website
- [x] Replace all Text Icons with animated Icons

**Comment by Alfagun74** [comment]
https://github.com/Phalcode/gamevault-app/pull/282

**Comment by Alfagun74** [comment]
Completed:

- [x] Add additional Text Field to Crash Report
- [x] Finish Donut Chart in GameSettings
- [x] Find Images with Google Button
  - [x] Gamename + " Game Box Art"
  - [x] Gamename + " Game Background Art"
- [x] Put image into drop zones
- [x] Fill up Space between other users progresses and the description
- [x] Implement upload via URL locally
- [x] Either make Auto-Color Algorithm only choose colors that have enough contrast with white text, or implement a system where the text color is automatically adjusted to the background color so this doesnt happen:
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/6cb20106-33fb-4c33-ab59-86edb8d586c0)
- [x] Disable/Remove Playbutton for Games that are not installed:
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/a564a1dc-ae8a-4679-b392-7cde8d3d5340)
- [x] Fix Scroll Bug (ask @Alfagun74)
- [x] Block adding same game to the download queue multiple times
- [x] Add link to "Report Issue" and "Github" on window bar
- [X] Clicking on users picture in game view should open community tab of user
- [x] Change Texts here
![Image](https://github.com/Phalcode/gamevault-app/assets/22225051/e4f85115-b08a-43c5-86ea-110b993d14bb)
"Title", "Size", "Release Date", "Metacritic Rating", "Average Playtime", "Recently Added"
- [X] Make all Profile Picutres Rounded Squares instead of fully round
- [x] Set Icon for Game Settings -> RAWG Integration
