### ISSUE TITLE
I want a theme like this

### ISSUE THREAD

**Issue by pppaapp** [Phalcode/gamevault-app#382]
![CleanShot 2023-06-22 at 21 06 15](https://github.com/Phalcode/gamevault-app/assets/31263588/6e62c9df-fcf8-4be9-954f-9124fbd08c58)

A theme called [VisioN](https://forums.launchbox-app.com/files/file/4041-vision/) in [launchbox](https://www.launchbox-app.com)

**Comment by Alfagun74** [comment]
Thanks for the suggestion. This is not a "theme" as we imagined it (currently themes are only color themes), but more of a complete redesign and reminds me of ticket #208. It is not planned at the moment because it would require a lot of work. Maybe we could consider implementing a simple big picture mode like this in the future though, if we should rewrite the client cross platform.
